spring:
  docker:
    compose:
      lifecycle-management: start_only
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatRoom
      username: user
      password: password
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem